name: Deploy latest Gooftuber Server
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Go test
      uses: actions/setup-go@v1
      with:
        go-version: 1.21.0
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -v ./...

  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE }}
        script: |
          cd
          ./update-server.sh
